Update input-groupadd

diff --git a/config/files/usr/etc/input/input-groupadd b/config/files/usr/etc/input/input-groupadd
--- a/config/files/usr/etc/input/input-groupadd
+++ b/config/files/usr/etc/input/input-groupadd
@@ -15,32 +15,26 @@ LOGFILE="/tmp/input-groupadd.log"
         exit 1
     fi
 
-    # Create the input group if it does not exist
-    if ! getent group input > /dev/null; then
+    # Check if the input group exists
+    if getent group input > /dev/null; then
+        echo "Group 'input' already exists."
+    else
+        echo "Creating group 'input'"
         groupadd -r input
         if [ $? -ne 0 ]; then
             echo "Failed to create group 'input'."
             exit 1
-        else
-            echo "Group 'input' created successfully."
         fi
-    else
-        echo "Group 'input' already exists."
     fi
 
-    # Add the determined user to the input group if not already a member
-    if ! id -nG "$target_user" | grep -qw "input"; then
-        echo "Adding user '$target_user' to group 'input'"
-        #  usermod -aG input "$target_user"
-        gpasswd -a "$target_user" input
-        if [ $? -ne 0 ]; then
-            echo "Failed to add user '$target_user' to group 'input'."
-            exit 1
-        else
-            echo "User '$target_user' added to group 'input' successfully."
-        fi
+    # Add the user to the input group
+    echo "Adding user '$target_user' to group 'input'"
+    usermod -aG input "$target_user"
+    if [ $? -ne 0 ]; then
+        echo "Failed to add user '$target_user' to group 'input'."
+        exit 1
     else
-        echo "User '$target_user' is already a member of group 'input'."
+        echo "User '$target_user' added to group 'input' successfully."
     fi
 
     echo "Script finished at $(date)"
